/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'id' : AlbumId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'coverBlobId' : [] | [string],
  'photoCount' : bigint,
}
export type AlbumId = string;
export interface Photo {
  'id' : PhotoId,
  'title' : string,
  'description' : string,
  'blobId' : string,
  'albumId' : AlbumId,
  'uploadedAt' : bigint,
}
export type PhotoId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[string, string, AlbumId, string], [] | [Photo]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlbum' : ActorMethod<[string, string], Album>,
  'deleteAlbum' : ActorMethod<[AlbumId], boolean>,
  'deletePhoto' : ActorMethod<[PhotoId], boolean>,
  'getAlbum' : ActorMethod<[AlbumId], [] | [Album]>,
  'getAlbums' : ActorMethod<[], Array<Album>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPhoto' : ActorMethod<[PhotoId], [] | [Photo]>,
  'getPhotos' : ActorMethod<[], Array<Photo>>,
  'getPhotosByAlbum' : ActorMethod<[AlbumId], Array<Photo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAsAdmin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateAlbum' : ActorMethod<
    [AlbumId, string, string, [] | [string]],
    boolean
  >,
  'updatePhoto' : ActorMethod<[PhotoId, string, string, AlbumId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];